#!/bin/bash

for num in `echo {00..99}`
do
  python grow_poly.py
  mv growing_strand.pdb strand_${num}.pdb
done

#This conditional is dependent on the last line of cap.pdb
for strand in `ls strand_??.pdb`
do
  if grep -q 'HC8C LEH A  17' $strand
  then
    continue
  else
    echo "$strand failed to be constructed!"
  fi
done
